name: SmartStart
version: 0.1a
description: Privodes a smarter way to restart the server.
author: psygate
main: com.psygate.smartstart.SmartStart
database: false
commands:
    telemetry:
        description: Provides telemetry about the server state.
        aliases: stel
        permission: smartstart.telemetry
        usage: /stel
    forcelimit:
        description: Provides telemetry about the server state.
        aliases: stfl
        permission: smartstart.forcelimit
        usage: /stfl
    forcetick:
        description: Provides telemetry about the server state.
        aliases: stft
        permission: smartstart.forcetick
        usage: /stft


permissions:
    smartstart.telemetry:
        description: Allows access to the telemetry command.
        default: op
    smartstart.forcelimit:
        description: Allows access to the force limit command.
        default: op
    smartstart.forcetick:
        description: Allows access to the force tick command.
        default: op
    smartstart.notifications:
        description: Will turn on verbose notification for that person.
        default: op
        